---

- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    npm_bin: /usr/local/bin/npm
    working_dir: /Users/ddcarr/projects/gen-cropcompass
    dist_dir: "{{working_dir}}/dist"
    branch: HEAD
    env: prod
    tld: www.cropcompass.org
    website_bucket: "{{tld}}"
    region: us-west-2
    repo: https://github.com/hackoregon/cropcompass-ui.git

  roles:
    - get-assets            #create working directory and pull the repo
    - install-dependencies  #install library run-time dependencies for gen
    - gen-website           #gen the website
    - deploy-to-s3          #deploy website to s3
