---

- name: clean up the working directory
  become: yes
  become_method: sudo
  file:
    path: "{{working_dir}}"
    state: absent

- name: create the working directory
  file:
    path: "{{working_dir}}"
    state: directory

- name: clone the repo
  git:
    repo: "{{repo}}"
    clone: yes
    dest: "{{working_dir}}"
    version: "{{branch}}"
    force: yes

- name: get the fonts
  command: "aws s3 cp s3://{{font_bucket}}/ {{working_dir}}/src/styles/fonts --recursive"
