---

- name: create public bucket for website
  s3:
    bucket: "{{website_bucket}}"
    region: "{{region}}"
    mode: create
    overwrite: no
    permission: public-read

- name: Upload to s3
  command: "aws s3 cp {{dist_dir}}/ s3://{{website_bucket}}/ --recursive --exclude \".git/*\" --exclude \".gitignore/*\" --exclude \"node_modules/*\""
