---

- name: create public bucket for website
  s3:
    bucket: "{{website_bucket}}"
    region: "{{region}}"
    mode: create
    overwrite: no
    permission: public-read

- name: clean up the working directory
  become: yes
  become_method: sudo
  file:
    path: "{{working_dir}}"
    state: absent

- name: create the working directory
  file:
    path: "{{working_dir}}"
    state: directory

- name: clone the repo
  git:
    repo: "{{repo}}"
    clone: yes
    dest: "{{working_dir}}"
    version: "{{branch}}"
    force: yes

- name: Install sass
  become: yes
  become_method: sudo
  command: "{{npm_bin}} install node-sass"
  args:
    chdir: "{{working_dir}}"

- name: Install nodemon
  become: yes
  become_method: sudo
  command: "{{npm_bin}} install nodemon"
  args:
    chdir: "{{working_dir}}"

- name: Install the app and libs
  become: yes
  become_method: sudo
  command: "{{npm_bin}} install"
  args:
    chdir: "{{working_dir}}"

- name: Compile Sass
  become: yes
  become_method: sudo
  command: "{{npm_bin}} run sass"
  args:
    chdir: "{{working_dir}}"

- name: Upload to s3
  command: "aws s3 cp {{working_dir}}/. s3://{{website_bucket}}/ --recursive --exclude \".git/*\" --exclude \".gitignore/*\" --exclude \"node_modules/*\""
  args:
    chdir: "{{working_dir}}"
