---
- name: Install postgress and configure for cropcompass
  become: yes
  become_method: su
  become_user: vagrant
  command: "/vagrant/scripts/postgresql.bash"
  args:
    chdir: "{{working_dir}}"
